project_id = "aewelwfgmuaptqixpogj"

[functions.discord-oauth]
verify_jwt = false

[functions.gaming-oauth]
verify_jwt = false

[functions.create-points-checkout]
verify_jwt = false

[functions.fetch-fortnite-stats]
verify_jwt = false
